/// Flutter icons JoyveeIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JoyveeIcons
///      fonts:
///       - asset: fonts/JoyveeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

class JoyveeIcons {
  JoyveeIcons._();

  static const _kFontFam = 'JoyveeIcons';
  static const String? _kFontPkg = null;

  static const _kFontFam2 = 'JoyveeIconsPack2';
  static const String? _kFontPkg2 = null;

  static const IconData messenger_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_outlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData micro_outlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photocamera_outlined = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_outlined = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocamera_outlined = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_filled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule_filled = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_filled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // second pack
  static const IconData vision_map = IconData(0xe800, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData pretzel = IconData(0xe801, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData grid = IconData(0xe802, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData pen = IconData(0xe803, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData moon = IconData(0xe804, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData lock_open = IconData(0xe806, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData exit = IconData(0xe807, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData bin = IconData(0xe808, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData file = IconData(0xe809, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData bell = IconData(0xe80a, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData videocamera_filled = IconData(0xe80b, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);

  static SvgPicture google = SvgPicture.asset("assets/svg/google.svg");
  static SvgPicture facebook = SvgPicture.asset("assets/svg/facebook.svg");
  static SvgPicture apple = SvgPicture.asset("assets/svg/apple.svg");
  static SvgPicture instagram = SvgPicture.asset("assets/svg/instagram.svg");
}
